### PR TITLE
Splitting Electric.md

### PR DESCRIPTION
**Pull request by Sudhanshu-Dubey14**
In Shops/Electric/Tools.md I would suggest to use the definition syntax as done in the first two points, but it is interfering with the bullets syntax. Any solution for this?

### CODE REVIEW

**Comment by Sudhanshu-Dubey14** [comment]
Ignore the Makefile as of now. I will change it after the structure of directories is completed.

**Comment by mandeeps708** [comment]
@Sudhanshu-Dubey14, it's not compulsory to create a commit with each change you make. For example of your another Pull Request, you could have renamed all the files in a single commit instead of one commit for each file renamed.

**Comment by Sudhanshu-Dubey14** [comment]
@mandeeps708 so one can save the changes they made without a commit?

**Comment by mandeeps708** [comment]
No. I meant you don't have to create a new commit for each small change. Similar things/changes can be combined within a single commit.

**Comment by hsrai** [comment]
You can save locally by using your editor. You may commit, even then nothing goes to GitServer. You may save file or many files files many times before doing a commit. You may have many commits before doing "Push" and then doing "Pull Request".

**Pull request merged**
